[button]
back = "⬅ 回到首页"
start_bind = "🔒 绑定账号"
start_unbind = "🔓 解绑账号"
start_export = "📤 导出账号"
start_import = "📥 导入账号"
start_my = "🧑 我的信息"
start_settings = "⚙ 设置"

settings_language = "🌏 语言"

[start]
desc = """
✨ 你好！[{{ .Username }}](tg://user?id={{ .ID }}) ✨

*E5SubBot 是专注于简化E5续订的 Bot*

[GitHub](https://github.com/iyear/E5SubBot) | [官方群组](https://t.me/e5subbot)

**公告:** ```{{ .Notice }}```
👇 点击按钮开始使用 👇
"""

[settings]
desc = "👇 请选择你的设置项"
language = """
🌏 当前语言为: *{{ . }}*

👇 请选择需要设置的语言
"""

[my]
desc = """
✨ 选择一个账户查看具体信息

绑定数: `{{ .Current }}`/`{{ .BindMax }}`
"""